site_name: DiverseDEV Coding Tank - 2023

theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: default 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: green
      accent: green
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: green
      accent: green

nav:
  - Sobre: index.md
  - Anotações de aulas:
    - Aula 01: "Anotacoes_de_aulas/Aula01.md"
  - Tutoriais:
    - VS Code: "Tutoriais/VSCode.md"

repo_url: https://github.com/AlunosDiverseDEV2023/CodingTank1
repo_name: CodingTank1

markdown_extensions:
- pymdownx.emoji
- pymdownx.tasklist
- pymdownx.mark
- pymdownx.tilde
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- admonition
- pymdownx.arithmatex:
    generic: true
- footnotes
- pymdownx.details
- pymdownx.superfences